[settings]
# (Josh) At time of writing the go backend is experimental. When it's promoted
# to stable this can be removed.
experimental = true
# (Josh) Testing shows that mise only generates new lockfile entries for the
# platform it is run on, so adding new tools on MacOS causes the CI runs to
# create a diff for the corresponding Linux entries. We can also assume that
# updating versions on one OS would leave the other(s) out of date. For now
# we'll rely on specifying exact versions here (or as exact as we feel is
# necessary) and revisit the lockfile if and when it improves and we feel it's
# needed.
lockfile = false
# (Josh) asdf plugins are just shell scripts that never work on Windows, which
# is one of our supported platforms.
disable_backends = ["asdf"]

[tools]
buf = "1.55.1"
go = "1.25"
"go:github.com/AlekSi/gocov-xml" = "1.0.0"
"go:github.com/axw/gocov/gocov" = "1.1.0"
"go:github.com/bufbuild/buf/cmd/protoc-gen-buf-breaking" = "1.55.1"
"go:github.com/bufbuild/buf/cmd/protoc-gen-buf-lint" = "1.55.1"
"go:github.com/edaniels/golinters/cmd/combined" = "0.0.5"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" = "2.20.0"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2" = "2.27.1"
"go:github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc" = "1.5.1"
golangci-lint = "2.6.2"
gotestsum = "1.10.0"                                                              # should be kept in sync with go.mod
jq = "1.8.1"
node = "18.20.8"
protoc = "21.12"
protoc-gen-go = "1.35.1"
protoc-gen-go-grpc = "1.5.1"

[alias]
buf = "ubi:bufbuild/buf"

[tasks.setup-cert]
description = "Create a self-signed cert and add it to the system trust store"
dir = "etc"
run = "bash ./setup_cert.sh"

[tasks.setup-priv-key]
description = "Create private keys for testing"
dir = "etc"
run = "bash ./setup_priv_key.sh"

[tasks.build-go]
alias = "build"
depends = ["buf-go"]
run = "go build ./..."

[tasks.buf-go]
run = ["buf lint", "buf generate"]

[tasks.lint-go]
alias = "lint"
wait_for = ["build-go"]
run = """
  {% raw %}
  #!/usr/bin/env bash
  set -x
  go mod tidy
  buf lint
  set +x
  export pkgs=`go list -f '{{.Dir}}' ./... | grep -v gen | grep -v proto` && echo "$pkgs" | xargs -t go vet -vettool=$(which combined)
  export GOGC=50 pkgs=`go list -f '{{.Dir}}' ./... | grep -v gen | grep -v proto` && echo "$pkgs" | xargs -t golangci-lint run $LINT_BUILD_TAGS -v --fix --config=./etc/.golangci.yaml
  {% endraw %}
"""

[tasks.cover]
run = "./etc/test.bash cover"

[tasks.test-go]
alias = "test"
run = "./etc/test.bash"

[tasks.list-example-echo-tasks]
hide = true
quiet = true
dir = "rpc/examples/echo"
run = """mise tasks ls -l -J | jq -r '.[] | select(.source | endswith("rpc/examples/echo/mise.toml")) | .name'"""

[tasks.example-echo]
dir = "rpc/examples/echo"
usage = """
complete "echo_task" run="mise run list-example-echo-tasks"
"""
run = "mise run {{ arg(name='echo_task') }}"
