name: Buf Push

on:
  # Triggers the workflow on pushes to the main branch
  push:
    paths:
      - 'proto/**'
    branches:
      - main

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buf-push:
    if: github.repository_owner == 'viamrobotics'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/viamrobotics/canon:amd64
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
        with:
          experimental: true
          install: false
      - name: Extract buf version from mise
        id: buf-version
        run:
          echo "version=$(mise tool ubi:bufbuild/buf --active)" >> $GITHUB_OUTPUT
      - uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99
        with:
          version: ${{ steps.buf-version.outputs.version }}
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}

  dispatch:
    needs: buf-push
    if: github.repository_owner == 'viamrobotics'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/viamrobotics/canon:amd64
    strategy:
      matrix:
        repo: ['viamrobotics/python-sdk','viamrobotics/rust-sdk']
    steps:
      - name: Notify Proto Watchers
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: protos-updated
          client-payload: '{"repo_name": "${{github.repository}}", "sha": "${{github.sha}}"}'
