name: NPM Publish @viamrobotics/rpc

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    container: ghcr.io/viamrobotics/rdk-devenv:amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: get grpc-web
        run: |
          curl --fail --location 'https://github.com/grpc/grpc-web/releases/download/1.5.0/protoc-gen-grpc-web-1.5.0-linux-x86_64' -o protoc-gen-grpc-web
          chmod +x protoc-gen-grpc-web
          sudo install -t /usr/local/bin protoc-gen-grpc-web

      - name: Install Build
        run: make build-web

      - name: Publish
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: rpc/js/package.json
