### Temporarily turned off due to an issue in CI.
### See: https://github.com/viamrobotics/goutils/actions/runs/3207545693/jobs/5242534039

# name: NPM Publish

# on:
#   push:
#     branches:
#       - main

# jobs:
#   publish:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v2.4.0
#         with:
#           persist-credentials: false

#       - name: Install and Build ğŸ”§
#         run: |
#           make build-web

#       - name: Publish ğŸš€
#         uses: JS-DevTools/npm-publish@v1
#         with:
#           token: ${{ secrets.NPM_TOKEN }} 
