name: NPM Publish @viamrobotics/rpc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: deps
        run: |
          # protoc
          curl --fail --location https://github.com/protocolbuffers/protobuf/releases/download/v28.0/protoc-28.0-linux-x86_64.zip -o protoc.zip
          unzip protoc.zip bin/protoc
          sudo install -t /usr/local/bin bin/protoc

          # grpc-web
          curl --fail --location https://github.com/grpc/grpc-web/releases/download/1.5.0/protoc-gen-grpc-web-1.5.0-linux-x86_64 -o protoc-gen-grpc-web
          chmod +x protoc-gen-grpc-web
          sudo install -t /usr/local/bin protoc-gen-grpc-web

      - name: Install Build
        run: make build-web

      - name: Publish
        uses: JS-DevTools/npm-publish@v2
        if: github.event_name == 'push' && github.ref_name == 'main'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: rpc/js/package.json
